{
 "title": "Deluge Metrics",
 "description": "A Deluge statistics dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Torrents (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrent_state_count{state=\"all\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torrents (active)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrent_state_count{state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torrents (paused)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrent_state_count{state=\"paused\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torrents (error)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrent_state_count{state=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_download_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_upload_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_free_space", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_num_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DHT nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_dht_nodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bandwidth utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "deluge_download_rate", "legendFormat": "Download" },
    { "expr": "-deluge_upload_rate", "legendFormat": "Upload" }
   ]
  },
  {
   "title": "Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Torrents by state",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "deluge_torrent_state_count", "legendFormat": "{{state}}" }
     ]
    },
    {
     "title": "Torrents by label",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrent_label_count{label=\"\"}",
       "legendFormat": "no_label"
      },
      {
       "expr": "deluge_torrent_label_count{label!=\"\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "deluge_num_connections", "legendFormat": "Connections" }
     ]
    },
    {
     "title": "DHT nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "deluge_dht_nodes", "legendFormat": "DHT Nodes" }
     ]
    },
    {
     "title": "Free space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "deluge_free_space", "legendFormat": "Free space" }
     ]
    },
    {
     "title": "Protocol bandwidth utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "deluge_download_protocol_rate", "legendFormat": "Protocol download" },
      { "expr": "-deluge_upload_protocol_rate", "legendFormat": "Protocol upload" }
     ]
    }
   ]
  }
 ]
}